[package]
name = "daily-sign"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64ct = "1.8.0"
ed25519-dalek = { version = "2.2.0", features = [ "pem", "pkcs8" ] }
gloo-file = "0.3.0"
gloo-timers = { version="0.3.0", features = [ "futures" ] }
gloo-utils = "0.2.0"
js-sys = "0.3.77"
rust-i18n = "3.1.5"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = [ "Clipboard", "Navigator", "CssStyleDeclaration", "HtmlElement" ] }
yew = { version = "0.21.0", features = ["csr"] }
