name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  gh_pages:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          # Optional version of trunk to install(eg. 'v0.21.14', 'latest')
          version: 'latest'
      - name: Build
        run: trunk build --release -M
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}